### ISSUE TITLE
Tests are only working with npm; failing with yarn

### ISSUE THREAD

**Issue by esteblock** [paltalabs/soroban-react#39]
If pakcages are installed with yarn, I get this error:

```bash
 yarn test
yarn run v1.22.19
$ npm run test --prefix=./packages/core

> @soroban-react/core@5.0.3 test
> yarn build && yarn jest

$ rm -rf dist
$ yarn prebuild && tsc
$ rm -rf dist
$ /home/wachuma/Blockchain/stellar/esteblock/soroban-react/node_modules/.bin/jest
 FAIL  tests/useSorobanReact.test.js
  ● Test suite failed to run

    Cannot find module 'react' from 'jest.setup.js'

      1 | const { JSDOM } = require('jsdom');
    > 2 | const React = require('react');
        |               ^
      3 | const { useContext } = require('react');
      4 | const { render } = require('react-dom');
      5 | const { renderHook } = require('@testing-library/react-hooks');

      at Resolver._throwModNotFoundError (../../node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.require (jest.setup.js:2:15)

 FAIL  tests/index.test.js
  ● Test suite failed to run

    Cannot find module 'react' from 'jest.setup.js'

      1 | const { JSDOM } = require('jsdom');
    > 2 | const React = require('react');
        |               ^
      3 | const { useContext } = require('react');
      4 | const { render } = require('react-dom');
      5 | const { renderHook } = require('@testing-library/react-hooks');

      at Resolver._throwModNotFoundError (../../node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.require (jest.setup.js:2:15)

 FAIL  tests/SorobanContext.test.js
  ● Test suite failed to run

    Cannot find module 'react' from 'jest.setup.js'

      1 | const { JSDOM } = require('jsdom');
    > 2 | const React = require('react');
        |               ^
      3 | const { useContext } = require('react');
      4 | const { render } = require('react-dom');
      5 | const { renderHook } = require('@testing-library/react-hooks');

      at Resolver._throwModNotFoundError (../../node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.require (jest.setup.js:2:15)

```

**Comment by esteblock** [comment]
npm install is also not working?

**Comment by esteblock** [comment]
Should we be married with only one package manager?
